[package]
name = "hpfile"
version = "0.1.1"
edition = "2021"
description = "Head-prunable file."
license = "MIT OR Apache-2.0"
repository = "https://github.com/qmdb/hpfile"
homepage = "https://github.com/qmdb/hpfile"


[dependencies]
anyhow = "1.0.86"
dashmap = "5.4.0"

